<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(                                                                                     
    'EasyXML\Module'
        => __DIR__ . '/Module.php',
    'EasyXML\Library\Array2XML'
        => __DIR__ . '/src/EasyXML/Library/Array2XML.php',
    'EasyXML\Library\XML2Array'
        => __DIR__ . '/src/EasyXML/Library/XML2Array.php',
    'EasyXML\Controller\Plugin\EasyXMLPlugin'
        => __DIR__ . '/src/EasyXML/Controller/Plugin/EasyXMLPlugin.php',
    'EasyXML\Controller\Plugin\Factory\EasyXMLPluginFactory'
        => __DIR__ . '/src/EasyXML/Controller/Plugin/Factory/EasyXMLPluginFactory.php',
    'EasyXML\Service\EasyXMLService'
        => __DIR__ . '/src/EasyXML/Service/EasyXMLService.php',
);
